services:
  api:
    build: ./WebApi
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - my-network

  apisearch:
    build: ./WebApiSearch
    depends_on:
      - api
    ports:
      - "5000:5000"
    networks:
      - my-network

  frontend: 
    build: ./WebFrontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - my-network
  
  db:
    build: ./db
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  
      MONGO_INITDB_ROOT_PASSWORD: example 
    networks:
      - my_network

volumes:
  mongo_data:

networks: 
  my-network: 
    driver: bridge
